FROM ubuntu:20.04

# Evitar interacciones durante la instalación
ENV DEBIAN_FRONTEND=noninteractive

# Actualizar e instalar dependencias
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libssh-dev \
    libjson-c-dev \
    libcurl4-openssl-dev \
    apache2 \
    net-tools \
    iproute2 \
    curl \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Crear directorio del proyecto
WORKDIR /opt/higurama

# Exponer puertos
EXPOSE 4444 80

# Comando por defecto
CMD ["/bin/bash"]